name: Save Estimate to Confluence

on:
  workflow_dispatch:
    inputs:
      clientName:
        description: "Client Name"
        required: true
      imageData:
        description: "Base64 Image Data"
        required: true

jobs:
  save-to-confluence:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Curl (Ensure it's available)
        run: sudo apt-get update && sudo apt-get install -y curl jq

      - name: Debug Environment Variables
        run: |
          echo "CLIENT_NAME=${{ github.event.inputs.clientName }}"
          echo "IMAGE_DATA length: ${#IMAGE_DATA}"

      - name: Send Data to Confluence
        run: |
          CLIENT_NAME="${{ github.event.inputs.clientName }}"
          IMAGE_DATA="${{ github.event.inputs.imageData }}"
          GHUB_PAT="${{ secrets.GHUB_PAT }}"  # ✅ Use GitHub Secret

          echo "Sending request to Confluence..."

          RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X POST "https://englebertltd.atlassian.net/wiki/rest/api/content" \
            -H "Authorization: Basic $(echo -n '${{ secrets.CONFLUENCE_USER }}:${{ secrets.CONFLUENCE_API_TOKEN }}' | base64)" \
            -H "Content-Type: application/json" \
            --data '{
              "type": "page",
              "title": "Fee Estimate - '"$CLIENT_NAME"'",
              "ancestors": [{ "id": "182911020" }],
              "space": { "key": "Clients" },
              "body": {
                "storage": {
                  "value": "<h1>Fee Estimate</h1><p>Client: '"$CLIENT_NAME"'</p><p><img src='"$IMAGE_DATA"' alt='Estimate Screenshot'></p>",
                  "representation": "storage"
                }
              }
            }')

          echo "HTTP Response Code: $RESPONSE"
          echo "Confluence API Response:"
          cat response.json || echo "No response file found"

          if [[ "$RESPONSE" -ne 200 && "$RESPONSE" -ne 201 ]]; then
            echo "ERROR: Failed to create page on Confluence!"
            exit 1
          fi

      - name: Debug Confluence Response
        run: cat response.json || echo "No response file found"
