name: Save Estimate to Confluence

on:
  issues:
    types: [opened]  # 🚀 This triggers the workflow when a new GitHub Issue is created

jobs:
  save-to-confluence:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Curl
        run: sudo apt-get update && sudo apt-get install -y curl jq

      - name: Extract GitHub Issue Data
        run: |
          CLIENT_NAME=$(echo '${{ github.event.issue.title }}' | sed 's/Estimate Request - //')
          IMAGE_DATA=$(echo '${{ github.event.issue.body }}' | sed 's/```//g')

          echo "Extracted Client Name: $CLIENT_NAME"
          echo "Extracted Image Data Length: ${#IMAGE_DATA}"

      - name: Send Data to Confluence
        run: |
          CLIENT_NAME=$(echo '${{ github.event.issue.title }}' | sed 's/Estimate Request - //')
          IMAGE_DATA=$(echo '${{ github.event.issue.body }}' | sed 's/```//g')

          echo "Sending request to Confluence..."

          RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X POST "https://englebertltd.atlassian.net/wiki/rest/api/content" \
            -H "Authorization: Basic $(echo -n '${{ secrets.CONFLUENCE_USER }}:${{ secrets.CONFLUENCE_API_TOKEN }}' | base64)" \
            -H "Content-Type: application/json" \
            --data '{
              "type": "page",
              "title": "Fee Estimate - '"$CLIENT_NAME"'",
              "ancestors": [{ "id": "182911020" }],
              "space": { "key": "Clients" },
              "body": {
                "storage": {
                  "value": "<h1>Fee Estimate</h1><p>Client: '"$CLIENT_NAME"'</p><p><img src='"$IMAGE_DATA"' alt='Estimate Screenshot'></p>",
                  "representation": "storage"
                }
              }
            }')

          echo "HTTP Response Code: $RESPONSE"
          cat response.json || echo "No response file found"

          if [[ "$RESPONSE" -ne 200 && "$RESPONSE" -ne 201 ]]; then
            echo "ERROR: Failed to create page on Confluence!"
            exit 1
          fi
