name: Save Estimate to Confluence

on:
  workflow_dispatch:
    inputs:
      clientName:
        description: "Client Name"
        required: true
      imageData:
        description: "Base64 Image Data"
        required: true

jobs:
  save-to-confluence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug GitHub Secrets
        run: echo "GHUB_PAT is available"
        env:
          GHUB_PAT: ${{ secrets.GHUB_PAT }}

      - name: Decode Image and Save Estimate to Confluence
        env:
          GHUB_PAT: ${{ secrets.GHUB_PAT }}
          CONFLUENCE_USER: ${{ secrets.CONFLUENCE_USER }}
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
        run: |
          CLIENT_NAME="${{ github.event.inputs.clientName }}"
          IMAGE_DATA="${{ github.event.inputs.imageData }}"

          echo "Running workflow with Client Name: $CLIENT_NAME"
          
          curl -X POST "https://englebertltd.atlassian.net/wiki/rest/api/content" \
            -H "Authorization: Basic $(echo -n '${{ env.CONFLUENCE_USER }}:${{ env.CONFLUENCE_API_TOKEN }}' | base64)" \
            -H "Content-Type: application/json" \
            --data '{
              "type": "page",
              "title": "Fee Estimate - '"$CLIENT_NAME"'",
              "ancestors": [{ "id": "182911020" }],
              "space": { "key": "Clients" },
              "body": {
                "storage": {
                  "value": "<h1>Fee Estimate</h1><p>Client: '"$CLIENT_NAME"'</p><p><img src='"$IMAGE_DATA"' alt='Estimate Screenshot'></p>",
                  "representation": "storage"
                }
              }
            }'

