name: Save Estimate to Confluence

on:
  workflow_dispatch:
    inputs:
      clientName:
        description: "Client Name"
        required: true

jobs:
  save-to-confluence:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y curl jq

      - name: Debug Input Variables
        run: |
          echo "CLIENT_NAME=${{ github.event.inputs.clientName }}"

      - name: Upload Screenshot to Confluence
        env:
          CONFLUENCE_URL: "https://englebertltd.atlassian.net/wiki"
          CONFLUENCE_USER: ${{ secrets.CONFLUENCE_USER }}
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
          PAGE_PARENT_ID: "182911020"
        run: |
          CLIENT_NAME="${{ github.event.inputs.clientName }}"
          
          echo "Uploading image to Confluence..."
          RESPONSE=$(curl -X POST "$CONFLUENCE_URL/rest/api/content/$PAGE_PARENT_ID/child/attachment" \
            -u "$CONFLUENCE_USER:$CONFLUENCE_API_TOKEN" \
            -H "X-Atlassian-Token: no-check" \
            -F "file=@fee-estimate.png")

          ATTACHMENT_ID=$(echo "$RESPONSE" | jq -r '.results[0].id')

          if [[ -z "$ATTACHMENT_ID" || "$ATTACHMENT_ID" == "null" ]]; then
            echo "ERROR: Image upload failed."
            exit 1
          fi

          echo "Uploaded Image ID: $ATTACHMENT_ID"

      - name: Create Confluence Page with Image
        env:
          CONFLUENCE_URL: "https://englebertltd.atlassian.net/wiki"
          CONFLUENCE_USER: ${{ secrets.CONFLUENCE_USER }}
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
          SPACE_KEY: "Clients"
          PAGE_PARENT_ID: "182911020"
        run: |
          IMAGE_URL="$CONFLUENCE_URL/download/attachments/$PAGE_PARENT_ID/fee-estimate.png"

          echo "Creating Confluence Page..."
          RESPONSE=$(curl -X POST "$CONFLUENCE_URL/rest/api/content" \
            -u "$CONFLUENCE_USER:$CONFLUENCE_API_TOKEN" \
            -H "Content-Type: application/json" \
            --data '{
              "type": "page",
              "title": "Fee Estimate - '"$CLIENT_NAME"'",
              "ancestors": [{ "id": "'"$PAGE_PARENT_ID"'" }],
              "space": { "key": "'"$SPACE_KEY"'" },
              "body": {
                "storage": {
                  "value": "<h1>Fee Estimate</h1><p>Client: '"$CLIENT_NAME"'</p><p><img src=\"'"$IMAGE_URL"'\" width=\"800px\"/></p>",
                  "representation": "storage"
                }
              }
            }')

          echo "Confluence Response: $RESPONSE"
